In [79]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


iris = datasets.load_iris()
data = iris.data



In [80]:
# Función para calcular la norma \(p\) de un vector \(x\)
def lp(x: np.ndarray, p=1) -> float:
    if p == "inf":
        return np.max(np.abs(x))
    return np.sum(np.abs(x)**p)**(1/p)

In [96]:
A = np.array([[3,2,-1],
              [3,-2,0],
              [3,2,1],
              [3,-2,0],
              [3,2,-1]])
def qr_normalization(A):
    n,m = A.shape
    transpose = False
    if n>m: 
        A = A.T
        n,m = A.shape
        transpose = True

    Q = []

    for i in range(n):
        omega_i = A[i]
        for q_i in Q:
            omega_i = omega_i - np.dot(np.dot(A[i], q_i), q_i)
        
        Q.append(omega_i/lp(omega_i, 2))



    R = np.zeros((n,n))
    for i in range(n):
        R[i,i] = lp(A[i],2)
        for j in range(i+1,n):
            R[i,j] = np.dot(A[j],Q[i])


    if transpose: 
        Q = np.array(Q).T
    else:
        Q = np.array(Q) 
    
    return Q,R

In [116]:
Q,R = qr_normalization(data)
R

array([[ 72.27620632,  36.98907477,  48.20064828,  15.60873291],
       [  0.        ,  37.82062929, -13.76876634,  -5.76407773],
       [  0.        ,   0.        ,  50.82036993,   4.47500611],
       [  0.        ,   0.        ,   0.        ,  17.38763929]])

In [121]:
datos = np.dot(Q,R)
print(datos[0])
print(data[0])

[ 5.1         6.8775277  -0.87439213  0.1269744 ]
[5.1 3.5 1.4 0.2]


In [118]:
np.linalg.qr(data)[1]

array([[-72.27620632, -36.98907477, -48.20064828, -15.60873291],
       [  0.        ,  -7.88722685,  13.76876634,   5.76407773],
       [  0.        ,   0.        ,   8.3563496 ,   4.47500611],
       [  0.        ,   0.        ,   0.        ,   2.33392057]])

In [120]:
np.linalg.norm(data[:,1])

37.820629291433