1) Implemente un algoritmo para calcular la factorización $Q R$ de una matríz basando en el proceso de ortogonalización de Grahm-Schmidt. El algoritmo debe recibir una matriz $A$ de tamaño $m \times n$ con $m \geq n$ y retornar una matriz $Q$ de tamaño $m \times n$ y una matriz triangular superior $R$ de tamaño $n \times n$, tales que $Q^t Q=I_n$ y $A=Q R$. Compare los resultados de su algoritmo con los de la función scipy.linalg.qr SciPy Manual.

In [2]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


iris = datasets.load_iris()
data = iris.data



In [3]:
# Función para calcular la norma \(p\) de un vector \(x\)
def lp(x: np.ndarray, p=1) -> float:
    if p == "inf":
        return np.max(np.abs(x))
    return np.sum(np.abs(x)**p)**(1/p)

# Función para realizar la factorizacion QR
def qr_normalization(A):
    n,m = A.shape
    transpose = False
    if n>m: 
        A = A.T
        n,m = A.shape
        transpose = True

    Q = []

    for i in range(n):
        omega_i = A[i]
        for q_i in Q:
            omega_i = omega_i - np.dot(np.dot(A[i], q_i), q_i)
        
        Q.append(omega_i/lp(omega_i, 2))

    R = np.zeros((n,n))
    for i in range(n):
        for j in range(i,n):
            R[i,j] = np.dot(A[j],Q[i])

    if transpose: 
        Q = np.array(Q).T
    else:
        Q = np.array(Q) 
    
    return Q,R

In [12]:
A = np.array([[3,2,-1],
              [3,-2,0],
              [3,2,1],
              [3,-2,0],
              [3,2,-1]])

Q,R = qr_normalization(A)  
print("Matriz Q calculada por metodo Propio: \n", Q)

#Comparacion con numpy para comprobar que la función está bien implementada
print("Matriz Q calcluada de numpy: \n", np.round(np.linalg.qr(A)[0],4))

Matriz Q calculada por metodo Propio: 
 [[ 0.4472136   0.36514837 -0.40824829]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837  0.81649658]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837 -0.40824829]]
Matriz Q calcluada de numpy: 
 [[-0.4472  0.3651  0.4082]
 [-0.4472 -0.5477 -0.    ]
 [-0.4472  0.3651 -0.8165]
 [-0.4472 -0.5477 -0.    ]
 [-0.4472  0.3651  0.4082]]


Revisando si se puede reobtener un dataset despues de haccerle normalizacion QR

In [6]:
Q,R = qr_normalization(data)
print("Matriz R calculada por metodo Propio: \n", R)

#Comparacion con numpy para comprobar que la función está bien implementada
print("Matriz R calcluada de numpy: \n", np.linalg.qr(data)[1])

Matriz R calculada por metodo Propio: 
 [[ 72.27620632  36.98907477  48.20064828  15.60873291]
 [  0.           7.88722685 -13.76876634  -5.76407773]
 [  0.           0.           8.3563496    4.47500611]
 [  0.           0.           0.           2.33392057]]
Matriz R calcluada de numpy: 
 [[-72.27620632 -36.98907477 -48.20064828 -15.60873291]
 [  0.          -7.88722685  13.76876634   5.76407773]
 [  0.           0.           8.3563496    4.47500611]
 [  0.           0.           0.           2.33392057]]


In [9]:
datos = np.dot(Q,R)
print("Matriz Q*R: \n", datos[0:5])
print("Datos reales: \n", data[0:5])

Matriz Q*R: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Datos reales: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


2) ¿Que pasa con la factorización QR cuando las columnas son linealmente dependientes?

In [28]:
A = np.array([[5,4,3,2],
              [2,3,4,4],
              [3,4,5,5],
              [10,8,6,4]] )

print("Rango de la matriz: ", np.linalg.matrix_rank(A))
print("Espacio columna de la matriz: ", np.linalg.matrix_rank(A.T))
Q,R = qr_normalization(A)  
print("Matriz Q calculada: \n", np.round(Q,4))
print("Matriz R calculada: \n", np.round(R,4))

Rango de la matriz:  3
Espacio columna de la matriz:  3
Matriz Q calculada: 
 [[ 0.6804  0.5443  0.4082  0.2722]
 [-0.5379 -0.0316  0.4746  0.696 ]
 [ 0.2847 -0.1898 -0.6644  0.6644]
 [ 0.2596 -0.1911 -0.6418  0.6958]]
Matriz R calculada: 
 [[ 7.3485  5.7155  7.6206 14.6969]
 [ 0.      3.5119  4.113  -0.    ]
 [ 0.      0.      0.0949 -0.    ]
 [ 0.      0.      0.     -0.    ]]


In [26]:
#caso 2
A = np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [0,0,0,0]])

Q,R = qr_normalization(A)  
print("Matriz Q calculada: \n", np.round(Q,4))
print("Matriz R calculada: \n", np.round(R,4))

Matriz Q calculada: 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [nan nan nan nan]]
Matriz R calculada: 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. nan]]


/tmp/ipykernel_36895/4014777140.py:23: RuntimeWarning: invalid value encountered in divide
  Q.append(omega_i/lp(omega_i, 2))


Aunque no en todos los casos, como se vio en el caso 1 que aunque fuera una matris $4\times 4$ y de rango 3, la matriz $R$ era de rango 4, y se pudo calcular exitosamente. Sin embargo en el caso 2 no se pudo realizar directamente la factorizacion QR, se observa como fallo el proceso al momento de intentar calcularla.

Si una matriz tiene columnas linealmente dependientes, es decir, si una o más columnas pueden expresarse como combinaciones lineales de las demás, entonces no se puede encontrar una factorización QR única. La razón detrás de esto es que en la matriz triangular superior (R) resultante, habrá elementos en la diagonal principal que son iguales a cero. Esto se debe a que una de las columnas dependientes linealmente puede expresarse como una combinación lineal de las demás, y esto se refleja en R como un elemento nulo en la diagonal.





3) Averigüe bajo cuales condiciones la factorización $Q R$ es única.

Sea A una matriz de $m\times n$ si A tiene n columnas independientes entonces la factorizacion es unica. Tambien si A es de tamaño $n \times n$ y es invertible tendra una unica factorización.