In [19]:
import numpy as np

In [20]:
def power_method(A, x=None, n=100, tolerance=0.001):
    """
    A: Matriz de entrada
    x: Vector inicial
    n: Numero de iteraciones
    tolerance: Tolerancia
    """
    k = 0
    if x is None:
        x = np.ones(A.shape[1])    

    while k < n and np.linalg.norm( np.dot(A,x) - x) > tolerance:
        x = np.dot(A,x)
        x = x/np.linalg.norm(x)
        k += 1

    return x

In [21]:
def power_inverse_method(A, x=None, n=100, tolerance=0.001):
    """
    A: Matriz de entrada
    x: Vector inicial
    n: Numero de iteraciones
    tolerance: Tolerancia
    """
    k = 0
    if x is None:
        x = np.ones(A.shape[1])    
    A_inv = np.linalg.inv(A)

    while k < n and np.linalg.norm( np.dot(A,x) - x) > tolerance:
        x = np.dot(A_inv,x)
        x = x/np.linalg.norm(x)
        k += 1

    return x

In [89]:
import scipy.linalg as sla

def shifted_power_inverse_method(A, mu, x=None, n=100, tolerance=0.001):
    """
    A: Matriz de entrada
    x: Vector inicial
    n: Numero de iteraciones
    tolerance: Tolerancia
    """

    k = 0
    if x is None:
        x = np.ones(A.shape[1])
        
    A = A - mu*np.eye(A.shape[0])   
    LU_factorization = sla.lu_factor(A)

    while k < n and np.linalg.norm( np.dot(A,x) - x) > tolerance:
        x = sla.lu_solve(LU_factorization,x)
        x = x/np.linalg.norm(x)
        k += 1

    return x

## Exercise 1:
Let A be the matrix from the Inverse Power Method example.
$$A=\begin{bmatrix}
9&-1&-3\\
0&6&0 \\
-6&3&6
\end{bmatrix}$$


In [90]:
A = np.array([[9,-1,-3],
              [0,6,0],
              [-6,3,6]])

(a) Use the Power Method to approximate the largest eigenvalue $λ_1$. Verify that the exact value of $λ_1$ is 12.


In [91]:
X = power_method(A, n=100, tolerance=0.0001)

print("Eigenvector is approximately:")
print(np.round(X,2),'\n')
print("Magnitude of the eigenvalue is approximately:")
print(round(np.linalg.norm(np.dot(A,X))),'\n')
print("Magnitude of the difference is:")
print( np.dot(A,X) - X)

Eigenvector is approximately:
[ 0.71  0.   -0.71] 

Magnitude of the eigenvalue is approximately:
12 

Magnitude of the difference is:
[ 7.77817459e+00  5.02028006e-29 -7.77817459e+00]


In [92]:
print("Largest Eigenvalue actual value:", np.linalg.eig(A).eigenvalues[0])
print("Largest Eigenvector actual value:", np.linalg.eig(A).eigenvectors[:,0])

Largest Eigenvalue actual value: 12.0
Largest Eigenvector actual value: [ 0.70710678  0.         -0.70710678]


(b) Apply the Inverse Power Method with a shift of $μ=10$. Explain why the results differ from those in the example.


In [93]:
X = shifted_power_inverse_method(A, mu=10, n=100, tolerance=0.0001)

print("Eigenvector is approximately:")
print(np.round(X,2),'\n')
print("Magnitude of the eigenvalue is approximately:")
print(round(np.linalg.norm(np.dot(A,X))),'\n')
print("Magnitude of the difference is:")
print( np.dot(A,X) - X)

Eigenvector is approximately:
[ 0.71  0.   -0.71] 

Magnitude of the eigenvalue is approximately:
12 

Magnitude of the difference is:
[ 7.77817459e+00  5.02028006e-29 -7.77817459e+00]


(c) Apply the Inverse Power Method with a shift of $μ=7.5$ and the initial vector given below. Explain why the sequence of vectors approach the eigenvector corresponding to $λ_1$

In [128]:
X = np.array([1,0,0])
X = shifted_power_inverse_method(A, mu=7.5, x = X, n=10000, tolerance=0.0001)

print("Eigenvector is approximately:")
print(np.round(X,2),'\n')
print("Magnitude of the eigenvalue is approximately:")
print(round(np.linalg.norm(np.dot(A,X))),'\n')
print("Magnitude of the difference is:")
print( np.dot(A,X) - X)

Eigenvector is approximately:
[ 1. -0. -0.] 

Magnitude of the eigenvalue is approximately:
11 

Magnitude of the difference is:
[ 8.  0. -6.]


## Exercise 2: 
Let B be the following matrix.$$
B=
\begin{bmatrix}
-2& -18 &6\\
-11& 3 & 11\\
-27&15&31
\end{bmatrix}$$


(a) Apply the Power Method and Inverse Power Method with shifts to approximate all eigenvalues of the matrix B. (Note that one of the eigenvalues of this matrix is negative.)


In [117]:
B = np.array([[-2,-18,6],
              [-11,3,11],
              [-27,15,31]])

X = power_method(B, n=100, tolerance=0.0001)

print("Largest Eigenvalue: ", round(np.linalg.norm(np.dot(B,X))),'\n')

X = power_inverse_method(B, n=100, tolerance=0.0001)

print("Smalest Eigenvalue: ", round(np.linalg.norm(np.dot(B,X))),'\n')

X = shifted_power_inverse_method(B, mu=-10, n=100, tolerance=0.0001)

print("Other Eigenvalue: ", -round(np.linalg.norm(np.dot(B,X))),'\n')


Largest Eigenvalue:  36 

Smalest Eigenvalue:  4 

Other Eigenvalue:  -8 



(b) Check your results using the eig function in SciPy.

In [120]:
import scipy
print("Autovalores reales: ", scipy.linalg.eig(B)[0])

[36.+0.j -8.+0.j  4.+0.j]
