# Problema 1

## 1.
Sea $\Omega$ un conjunto finito. Demuestre que la distancia Jaccard en $\wp(\Omega)$ definida como
$$
d(A, B):=\frac{|A \triangle B|}{|A \cup B|},
$$
define una métrica.

### Demostracion

Para demostrar que la distancia de Jaccard es una metrica se deben demostrar que cumple las siguentes propiedades:

1. No-negatividad: $d(A,B) \geq 0$ para todo $A,B \in \wp(\Omega)$
2. Coincidencia: $d(A,B) = 0$ si y solo si $A = B$
3. Simetria: $d(A,B) = d(B,A)$ para todo $A,B \in \wp(\Omega)$
4. Desigualdad Triangular: $d(A,B) \leq d(A,C) + d(C,B)$ para todo $A,B,C \in \wp(\Omega)$

Demostacion:

1. **No-negatividad**:
    $$
    d(A,B) = \frac{|A \triangle B|}{|A \cup B|} \geq 0
    $$
    Dado a que tanto el numerador como el denominador son positivos

2. **Coincidencia**:

$$
d(A,B) = 0 \iff |A \triangle B| = 0 \iff A = B
$$

3. **Simetria**:

$$
d(A,B) = \frac{|A \triangle B|}{|A \cup B|} = \frac{|B \triangle A|}{|B \cup A|} = d(B,A)
$$

4. **Desigualdad Triangular**:

    $$
    d(A,B) = \frac{|A \triangle B|}{|A \cup B|} \leq \frac{|A \triangle C| + |C \triangle B|}{|A \cup C| + |C \cup B|} \leq \frac{|A \triangle C|}{|A \cup C|} + \frac{|C \triangle B|}{|C \cup B|} = d(A,C) + d(C,B)
    $$

Por tanto la distancia de Jaccard si es una metrica

--------------------------


## 2.
 Sea $Q$ una matriz tal que $Q^t Q=I$, demuestre que $Q$ preserva magnitudes y ángulos respecto al producto punto.

### Demostracion

Dado que $Q^t Q = I$, la matriz $Q$ es una matriz ortogonal.

**Preservación de magnitudes:**

Para demostrar que $Q$ preserva magnitudes, consideremos un vector $v$, y su imágenes bajo la aplicación de $Q$, denotada como $Qv$. Queremos demostrar que $\|Qv\| = \|v\|.

$$||Qv||^2 = (Qv)^t(Qv) = v^t Q^t Qv = v^t Iv = v^t v = ||v||^2$$

Por lo tanto, $Q$ preserva magnitudes.

**Preservación de ángulos:**

Para demostrar que $Q$ preserva ángulos, consideremos dos vectores $v$ y $w$ con ángulo $\theta$ entre ellos. Queremos demostrar que el ángulo entre $Qv$ y $Qw$ también es $\theta$.

$$ \cos(\theta) = \frac{v \cdot w}{||v|| \cdot ||w||} $$

Ahora, consideremos $Qv \cdot Qw$:

$$ Qv \cdot Qw = (Qv)^t(Qw) = v^t Q^t Qw = v^t I w = v \cdot w $$

Dividimos ambos lados por \(||Qv|| \cdot ||Qw||\), por la preservacion de magnitudes:

$$ \cos(\theta) = \frac{Qv \cdot Qw}{||Qv|| \cdot ||Qw||} $$

Por lo tanto $Q$ preserva angulos.

-----------

## 3. 
Demuestre que la norma matricial inducida por la norma euclidiana es igual a el mayor valor singular.

### Demostracion

Sea A una matriz de tamaño $m \times n$. La norma inducida se define como:

$$||A|| = \sup \{ ||Ax|| : ||x|| = 1 \}$$

Ahora, consideremos lo siguiente:

$$||Ax||^2 = (Ax)^T(Ax) = x^T(A^TA)x$$

Dado que $A^TA$ es una matriz simétrica definida positiva, su descomposicion en valores singulares tiene la siguiente forma $ A = V \Sigma V^T$, donde:
- $\Sigma$ es una matriz diagonal de tamaño $m \times n$ con los valores singulares en la diagonal, y
- $V$ es una matriz ortogonal de tamaño $n \times n$.

Por tanto se tiene que:
$$x^T(A^TA)x = x^T (V \Sigma V^T)x$$
Ahora definimos $V^T x = y$ obtenemos la expresion:
$$x^T V \Sigma V^T x = y^T \Sigma y =  \sum_i \lambda_i y_i^2$$
Esto implica que:
$$\|Ax\|^2 \leq \lambda_{max} y^Ty = \lambda_{max} x^TV^TVx = \lambda_{max} $$
Esto anterior se debe a que $V^TV = I$ al $V$ ser ortogonal y por la definición de $x$ tenemos que $\|x\| = x^Tx = 1$

Para finalizar la demostracion tomamos a $x = v_{max}$ donde $v_{max}$ es el autovector correspondiente al mayor autovalor. De esta manera se obtiene que $\|Ax\|^2 = \lambda_{max}$. 

Finalmente tenemos entonces que $\|A\|_2 = \sqrt{\lambda_{max} (A^TA)}$. O que la norma eculideana inducida es igual al mayor valor singular de una matriz

# Problema 2

1. Implemente un algoritmo para calcular los valores y vectores propios de una matriz simétrica $A$ a partir de la siguiente idea:
Inicie con $A_0=A$, en el paso $k$ calcule la descomposición QR de $A_k=Q_k R_k$ y defina $A_{k+1}=R_k Q_k$.

In [3]:
import numpy as np

def symmetrical_matrix_eigenvectors(matrix, tolerance):
    A_k = matrix
    Q_total = np.eye(A_k.shape[0])

    while True:     
        Q,R = np.linalg.qr(A_k)

        if np.linalg.norm(A_k - np.dot(R,Q)) < tolerance:
            return np.diag(A_k), -Q_total
        
        A_k = np.dot(R,Q)
        Q_total = np.dot(Q_total, Q)
        

In [35]:
A = np.array([[1,2,3,4],
              [4,5,6,7],
              [7,8,7,6],
              [4,2,3,4]]) * 0.1

A = A @ A.T

eig_val, eig_vec = symmetrical_matrix_eigenvectors(A, 0.00001)

In [32]:
np.round(eig_vec@np.diag(A_k),2)

array([[-1.01, -0.06, -0.01,  0.  ],
       [-2.19, -0.05, -0.01, -0.  ],
       [-2.74,  0.06, -0.01,  0.  ],
       [-1.27, -0.01,  0.03,  0.  ]])

In [34]:
np.round(A@eig_vec,2)

array([[-1.01, -0.06, -0.01,  0.  ],
       [-2.19, -0.05, -0.01, -0.  ],
       [-2.74,  0.06, -0.01, -0.  ],
       [-1.27, -0.01,  0.03, -0.  ]])

In [5]:
np.round(np.linalg.eig(A)[0],2), np.round(np.linalg.eig(A)[1],2)

(array([3.86, 0.1 , 0.  , 0.03]),
 array([[-0.26, -0.59,  0.72, -0.25],
        [-0.57, -0.48, -0.65, -0.15],
        [-0.71,  0.64,  0.2 , -0.22],
        [-0.33, -0.09,  0.13,  0.93]]))

In [6]:
np.round(A_k,2), np.round(Q,2)

(array([3.86, 0.1 , 0.03, 0.  ]),
 array([[-0.26, -0.59, -0.25,  0.72],
        [-0.57, -0.48, -0.15, -0.65],
        [-0.71,  0.64, -0.22,  0.2 ],
        [-0.33, -0.09,  0.93,  0.13]]))

Este algoritmo es como una version mas sofisticada del algoritmo de potencias hecho en talleres anteriories. Recordemos la definicion de los autovalores y autovectores:
$$ A v = A \lambda$$ donde $v$ es un autovector y $\lambda$ un autovalor. Como se utiliza descomposicion QR para renormalizar Y ortogonalizar la matriz cada vez se esta funcionando con una base de vectores completa. Tambien hay que considerar que estamos trabajando con una matriz simetrica $A$, por tanto 

---------

2. Cálcule los valores propios y los valores singulares para las siguientes matrices:
$$
A=\left(\begin{array}{llll}
0 & 1 & 0 & 0 \\
0 & 0 & 2 & 0 \\
0 & 0 & 0 & 3 \\
0 & 0 & 0 & 0
\end{array}\right) \quad B=\left(\begin{array}{cccc}
0 & 1 & 0 & 0 \\
0 & 0 & 2 & 0 \\
0 & 0 & 0 & 3 \\
0.001 & 0 & 0 & 0
\end{array}\right)
$$

In [17]:
A = np.array([[0,1,0,0],
             [0,0,2,0],
             [0,0,0,3],
             [0,0,0,0]])

B = np.array([[0,1,0,0],
            [0,0,2,0],
            [0,0,0,3],
            [0.001,0,0,0]])


In [18]:
singular_values_A = np.linalg.svd(A, compute_uv=False)
singular_values_B = np.linalg.svd(B, compute_uv=False)

print("Valores Singulares de A:", singular_values_A)
print("Valores Singulares de B:", singular_values_B)

Valores Singulares de A: [3. 2. 1. 0.]
Valores Singulares de B: [3.e+00 2.e+00 1.e+00 1.e-03]


Como ambas matrices tienen 0 en todos los valores de cada fila menos uno, los valores singulares son los mismos.

In [19]:
eigenvalues_A = np.round(np.linalg.eigvals(A), 2)
eigenvalues_B = np.round(np.linalg.eigvals(B), 2)

print("Valores Propios de A:", eigenvalues_A)
print("Valores Propios de B:", eigenvalues_B)


Valores Propios de A: [0. 0. 0. 0.]
Valores Propios de B: [-0.28+0.j   -0.  +0.28j -0.  -0.28j  0.28+0.j  ]


Como no es una matriz diagonal y tiene tanto 0 los valores obtenidos son imaginarios para B y para A por fuera de un rango menor que el tamaño y la primera fila es 0 en su totalidad, los autovalores son 0, sin embargo si se cambian las matrices a que sean diagonales mediante un cambio de la ultima fila a la primera, de la siguiente forma, se pueden calcular los autovalores y estos seran iguales a los valores singulares calculados anteriormente.

In [22]:
A = np.array([[0,0,0,0],
              [0,1,0,0],
             [0,0,2,0],
             [0,0,0,3]])

B = np.array([[0.001,0,0,0],
              [0,1,0,0],
              [0,0,2,0],
              [0,0,0,3]])

eigenvalues_A = np.linalg.eigvals(A)
eigenvalues_B = np.linalg.eigvals(B)

print("Valores Propios de A:", eigenvalues_A)
print("Valores Propios de B:", eigenvalues_B)

Valores Propios de A: [0. 1. 2. 3.]
Valores Propios de B: [1.e-03 1.e+00 2.e+00 3.e+00]


# Problema 3